project:
  type: default
  output-dir: docs

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    self-contained: true
    theme: flatly
    number-sections: false
    
  pdf:
    documentclass: article
    fontsize: 12pt
    mainfont: "Times New Roman"
    linestretch: 1.5
    toc: false
    colorlinks: true
    pdf-engine: xelatex
    number-sections: false
    geometry:
      - margin=1in
    
  docx:
    toc: false
    reference-doc: joad_data_paper_template_0-3-OTH.docx
    number-sections: false

csl: apa.csl
bibliography: references.bib
link-citations: true